### PR TITLE
Extend available placeholders for layouts / Cleanup Duration formats

### LINKED ISSUE #607: %NAME% Do not work on ban layout
%NAME% Do not work on ban layout. But I really need it to identify an account that has been blocked from just one screenshot of the lock screen

_What version of AdvancedBan (`/AdvancedBan`) are you using?_ 2.3.0
 
 
_What kind of server do you have (`Bungeecord/single server`)?_ single server
 
 
_What server version (/version) are you using?_ PurPur 1.19.3

_Please provide the EXACT steps required to reproduce the problem..._
1. Paste in the layout %NAME%
2. ban player
3. see locksreen layout

image
image

### LINKED ISSUE #610: please Add the %NAME% variable (Players who have been penalized)
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.3.0
 
_What kind of server do you have (`Bungeecord/single server`)?_
 bc
 
_What server version (/version) are you using?_
1.8.8

_Please provide the EXACT steps required to reproduce the problem..._
1. please Add the %NAME% variable
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_

_Add any additional information below._

### PR DESCRIPTION
**Pull request by Hopefuls**
This pull request implements the following:

- ~~Improve duration display (redact times that have null values, for example 10 Days, 0 Hours)~~
- Implement Duration Placeholder that allows display of the full duration along with the "time left"

Closes #607 and #610

image

### CODE REVIEW

**Comment by Hopefuls** [comment]
> Improve duration display (redact times that have null values, for example 10 Days, 0 Hours)
This cannot be implemented right now, since handling timestamps is hardcoded within the layouts too, this has to be implemented differently.

**Comment by Hopefuls** [comment]
Testing copilot stuff, ignore comment, it is totally fine

File: core/src/main/java/me/leoko/advancedban/utils/Punishment.java [hunk 1]
```diff
@@ -148,7 +148,8 @@ private void announce(int cWarnings) {
                 getType().getName() + ".Notification",
                 "OPERATOR", getOperator(),
                 "PREFIX", mi.getBoolean(mi.getConfig(), "Disable Prefix", false) ? "" : MessageManager.getMessage("General.Prefix"),
-                "DURATION", getDuration(true),
+                "DURATION", getDuration(false),
```
Comment (DevLeoko) [inline core/src/main/java/me/leoko/advancedban/utils/Punishment.java]: You should probably keep `fromStart` here `true` as well. It might take a few ms from creating the punishment to announcing it, which can cause this to be a second less than the total time and look ugly.
Maybe also add a quick comment explaining the reasoning to prevent confusion in the future.

**Review by DevLeoko — CHANGES_REQUESTED** [review]

File: core/src/main/java/me/leoko/advancedban/utils/Punishment.java (hunk 1 above)
Comment (Hopefuls) [reply core/src/main/java/me/leoko/advancedban/utils/Punishment.java]: This is only announced once, correct?

Good point though, will look into this right now

Comment (Hopefuls) [reply core/src/main/java/me/leoko/advancedban/utils/Punishment.java]: Looks good:

image

**Review by DevLeoko — APPROVED** [review]

**Comment by DevLeoko** [comment]
LGTM, can be merged 👍 thanks!
